from preprocess.step_0_bikedataconstructor import construct_bike_sequence
from preprocess.step_0_taxi_sequenceconstructor import construct_taxi_sequence
from preprocess.step_1_clustering import clustering
from preprocess.step_2_signalsequenceconstructor import main


construct_bike_sequence()
construct_taxi_sequence()
clustering()
main()